### ISSUE TITLE
packager/tool/pssh is broken

### ISSUE THREAD

**Issue by kqyang** [google/shaka-packager#162]
❯ ./pssh-box.py --content-id 1234 --provider widevine --widevine-system-id
Cannot find proto file, make sure to build first
Traceback (most recent call last):
  File "./pssh-box.py", line 29, in <module>
    import widevine_pssh_data_pb2  # pylint: disable=g-import-not-at-top
  File "/usr/local/google/home/kqyang/source/packager3/src/packager/tools/pssh/../../../out/Release/pyproto/packager/media/base/widevine_pssh_data_pb2.py", line 9, in <module>
    from google.protobuf import symbol_database as _symbol_database
ImportError: cannot import name symbol_database

**Comment by kqyang** [comment]
This happens only if protobuf is installed in the system. The script would use the installed version of the protobuf which is not compatible with the script.
