### ISSUE TITLE
Packaging Error: 8 (PARSER_FAILURE): Cannot parse media file

### ISSUE THREAD

**Issue by ksuhiyp** [google/shaka-packager#668]
```
const HD= 's3://dash-hls-adaptive/HD-sample.webm'
const FSD= 's3://dash-hls-adaptive/FSD-sample.webm'
const SD= 's3://dash-hls-adaptive/SD-sample.webm'

```
packager args 
```
 const args =
        `in=SD,stream=audio,output=${audioPath},drm_label=AUDIO \\
        in=SD,stream=video,output=${SD_protectedPath},drm_label=SD \\
        in=FSD,stream=video,output=${FSD_protectedPath},drm_label=SD \\
        in=HD,stream=video,output=${HD_protectedPath},drm_label=HD \\
        --base_urls  https://s3-eu-west-1.amazonaws.com/dash-hls-adaptive/${lecture.id}/packagedFiles/ \\
    --clear_lead 0 \\
    --enable_raw_key_encryption \\
    --keys label=AUDIO:key_id=${ENV.AUDIO_KEY_ID}:key=${ENV.AUDIO_KEY},label=SD:key_id=${ENV.SD_KEY_ID}:key=${ENV.SD_KEY},label=HD:key_id=${ENV.HD_KEY_ID}:key=${ENV.HD_KEY} \\
   --mpd_output ${manifestPath}`
```

error

```
(node:259036) UnhandledPromiseRejectionWarning: Error: [1023/004511:INFO:demuxer.cc(88)] Demuxer::Run() on file '/tmp/2d3ae1a526175c3aec72327049c4fe52.'.
[1023/004511:INFO:demuxer.cc(160)] Initialize Demuxer for file '/tmp/2d3ae1a526175c3aec72327049c4fe52.'.
[1023/004511:INFO:demuxer.cc(88)] Demuxer::Run() on file '/tmp/5460d68c2b94777e55678a5668b86dc9.'.
[1023/004511:INFO:demuxer.cc(160)] Initialize Demuxer for file '/tmp/5460d68c2b94777e55678a5668b86dc9.'.
[1023/004511:INFO:demuxer.cc(88)] Demuxer::Run() on file '/tmp/f525ec36b5e5dec8af6cb0b117165a70.'.
[1023/004511:INFO:demuxer.cc(160)] Initialize Demuxer for file '/tmp/f525ec36b5e5dec8af6cb0b117165a70.'.
[1023/004511:ERROR:webm_cluster_parser.cc(329)] Got a block with a timecode before the previous block.
[1023/004511:ERROR:webm_cluster_parser.cc(329)] Got a block with a timecode before the previous block.
[1023/004511:ERROR:webm_cluster_parser.cc(329)] Got a block with a timecode before the previous block.
[1023/004511:ERROR:packager_main.cc(523)] Packaging Error: 8 (PARSER_FAILURE): Cannot parse media file /tmp/f525ec36b5e5dec8af6cb0b117165a70.

```

**Comment by ksuhiyp** [comment]
All the samples are AV1 wrapped in webm container, audio codec is opus

**Comment by kqyang** [comment]
@ksuhiyp There are problems in your test content:

> [1023/004511:ERROR:webm_cluster_parser.cc(329)] Got a block with a timecode before the previous block.

Can you fix the test content?

**Comment by ksuhiyp** [comment]
I am using libsvtav1 plugin for ffmpeg, args are 
```
'-vf', 'scale=1280:720', '-movflags', '+faststart', '-c:a', 'libopus', "-forced-idr", "1", '-c:v', 'libsvt_av1', '-f', 'webm', out_HD,
        '-vf', 'scale=720:480', '-movflags', '+faststart', '-c:a', 'libopus', "-forced-idr", "1", '-c:v', 'libsvt_av1', '-f', 'webm', out_FSD,
        '-vf', 'scale=480:360', '-movflags', '+faststart', '-c:a', 'libopus', "-forced-idr", "1", '-c:v', 'libsvt_av1', '-f', 'webm', out_SD
```
What does Got a block with a timecode before the previous block. means?

**Comment by ksuhiyp** [comment]
Ok, samples seem to be corrupted, there seem to be somthing wrong in ffmpeg args
thanks

**Comment by ksuhiyp** [comment]
Ok, I've generated a new samples and there playback is ok on VLC

Here are the new AV1 samples
 
s3://dash-hls-adaptive/baec1fc1252c7f9e68014ef4d92e1534.
s3://dash-hls-adaptive/882789e7fac3673578526f03816141d6.
s3://dash-hls-adaptive/5110db8b4b526d1d5235893f0a1f54c0.

```
(node:101691) UnhandledPromiseRejectionWarning: Error: [1024/002501:INFO:demuxer.cc(88)] Demuxer::Run() on file '/tmp/5110db8b4b526d1d5235893f0a1f54c0.'.
[1024/002501:INFO:demuxer.cc(160)] Initialize Demuxer for file '/tmp/5110db8b4b526d1d5235893f0a1f54c0.'.
[1024/002501:INFO:demuxer.cc(88)] Demuxer::Run() on file '/tmp/882789e7fac3673578526f03816141d6.'.
[1024/002501:INFO:demuxer.cc(160)] Initialize Demuxer for file '/tmp/882789e7fac3673578526f03816141d6.'.
[1024/002501:INFO:demuxer.cc(88)] Demuxer::Run() on file '/tmp/baec1fc1252c7f9e68014ef4d92e1534.'.
[1024/002501:INFO:demuxer.cc(160)] Initialize Demuxer for file '/tmp/baec1fc1252c7f9e68014ef4d92e1534.'.
[1024/002501:ERROR:webm_cluster_parser.cc(329)] Got a block with a timecode before the previous block.
[1024/002501:ERROR:webm_cluster_parser.cc(329)] Got a block with a timecode before the previous block.
[1024/002501:ERROR:webm_cluster_parser.cc(329)] Got a block with a timecode before the previous block.
[1024/002501:ERROR:packager_main.cc(523)] Packaging Error: 8 (PARSER_FAILURE): Cannot parse media file /tmp/5110db8b4b526d1d5235893f0a1f54c0.

    at _packageTranscodedFiles (/home/suhayb/repos/hisas/api/src/controllers/LectureController.js:209:15)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
warning.js:18
(node:101691) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
warning.js:18
(node:101691) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kqyang** [comment]
@ksuhiyp How are the files generated? They are still malformed as WebM does not support time going backwards

```log
[1024/002501:ERROR:webm_cluster_parser.cc(329)] Got a block with a timecode before the previous block.
```

**Comment by ksuhiyp** [comment]
FFmpeg, here are the args

    const args = ['-y', '-i', inputStream,

        '-vf', 'scale=1280:720', '-movflags', '+faststart', '-c:a', 'libopus', "-forced-idr", "1", '-c:v', 'libsvt_av1', '-f', 'webm', out_HD,
        '-vf', 'scale=720:480', '-movflags', '+faststart', '-c:a', 'libopus', "-forced-idr", "1", '-c:v', 'libsvt_av1', '-f', 'webm', out_FSD,
        '-vf', 'scale=480:360', '-movflags', '+faststart', '-c:a', 'libopus', "-forced-idr", "1", '-c:v', 'libsvt_av1', '-f', 'webm', out_SD

    ]

    const ffmpeg = spawn('ffmpeg', args);

**Comment by ksuhiyp** [comment]
Here is a log file for a random sample generated with FFmpeg
[log.txt](https://github.com/google/shaka-packager/files/3767636/log.txt)
Notice the` [webm @ 0x5564a16d6a00] Non-monotonous DTS in output stream 0:0; previous: 1720, current: 1440; changing to 1720. This may result in incorrect timestamps in the output file.`

**Comment by kqyang** [comment]
Yes, it is. It is possible to workaround the problem by ignoring or adjusting these samples, but it will still result in problematic playback. So please fix your content!

**Comment by ksuhiyp** [comment]
Dear @kqyang I've got rid of this  Non-monotonous DTS in output stream 0:0 notice by removing gop option in ffmpeg, then i started a fresh packaging process with new sample 

source sample info
```
[1025/230540:INFO:demuxer.cc(88)] Demuxer::Run() on file 'input.mp4'.
[1025/230540:INFO:demuxer.cc(160)] Initialize Demuxer for file 'input.mp4'.

File "input.mp4":
Found 1 stream(s).
Stream [0] type: Video
 codec_string: avc1.4d401f
 time_scale: 24000
 duration: 3386383 (141.1 seconds)
 is_encrypted: false
 codec: H264
 width: 1280
 height: 720
 pixel_aspect_ratio: 1:1
 trick_play_factor: 0
 nalu_length_size: 4

Packaging completed successfully.
```
**same sample encoded to AV1 using ffmpeg libsvt plugin and its packager info shows the error**
```
[1025/230625:INFO:demuxer.cc(88)] Demuxer::Run() on file 'out.webm'.
[1025/230625:INFO:demuxer.cc(160)] Initialize Demuxer for file 'out.webm'.

File "out.webm":
Found 1 stream(s).
Stream [0] type: Video
 codec_string: av01.0.05M.08
 time_scale: 1000000
 duration: 141100000 (141.1 seconds)
 is_encrypted: false
 codec: AV1
 width: 1280
 height: 720
 pixel_aspect_ratio: 1:1
 trick_play_factor: 0
 nalu_length_size: 0

[1025/230625:ERROR:webm_cluster_parser.cc(329)] Got a block with a timecode before the previous block.
Packaging completed successfully.

```
I need to know what is exactly Got a block with a timecode before the previous block. means in packager and how to reproduce this error in ffmpeg or any probing tools in order to open an issue to SVTAV1

**Comment by kqyang** [comment]
It means the timestamp going backwards, which is not allowed by WebM. You can use the below command to dump the timestamps:

```shell
ffprobe -select_streams v -show_packets -show_entries packet=flags,pts_time,dts_time -of csv=p=0 <file>
```

**Comment by ksuhiyp** [comment]
Dear @kqyang here is the output of the timestmps for yet another sample that packager throws the same error on. Can you help me identify backward values?
[timestamp.log](https://github.com/google/shaka-packager/files/3774764/timestamp.log)

**Comment by kqyang** [comment]
It is everywhere in the log, e.g. look at the second and the third sample.

```
0.000000,0.000000,K_
0.667000,0.667000,__
0.334000,0.334000,__
0.167000,0.167000,__
```
