### ISSUE TITLE
Issue while trying to build on Ubuntu 19.10

### ISSUE THREAD

**Issue by sr1990** [google/shaka-packager#699]
## System info
**Operating System**: Ubuntu 19.10. 
**Shaka Packager Version**: latest

## Issue and steps to reproduce the problem
Following steps at: https://github.com/google/shaka-packager/blob/master/docs/source/build_instructions.md
$ gclient config https://www.github.com/google/shaka-packager.git --name=src --unmanaged
$ gclient sync

What is the expected result?
Build successful 
Didn't see any issue with Ubuntu 16.04

What happens instead?
Get the following response: 

Syncing projects: 100% (20/20), done.                                             

```
________ running 'vpython src/packager/build/linux/sysroot_scripts/install-sysroot.py --running-as-hook' in '/home/usr/Desktop/Projects/VideoProjects/shaka/shaka_packager'
Installing Debian Wheezy amd64 root image: /home/usr/Desktop/Projects/VideoProjects/shaka/shaka_packager/src/packager/build/linux/debian_wheezy_amd64-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/c52471d9dec240c8d0a88fa98aa1eefeee32e22f/debian_wheezy_amd64_sysroot.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 41.6M  100 41.6M    0     0  9352k      0  0:00:04  0:00:04 --:--:--  9.9M
Installing Debian Wheezy i386 root image: /home/usr/Desktop/Projects/VideoProjects/shaka/shaka_packager/src/packager/build/linux/debian_wheezy_i386-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/c52471d9dec240c8d0a88fa98aa1eefeee32e22f/debian_wheezy_i386_sysroot.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 44.6M  100 44.6M    0     0  9286k      0  0:00:04  0:00:04 --:--:-- 9449k
Hook 'vpython src/packager/build/linux/sysroot_scripts/install-sysroot.py --running-as-hook' took 11.51 secs
Running hooks:  60% ( 3/ 5) clang        
________ running 'vpython src/packager/tools/clang/scripts/update.py --if-needed' in '/home/usr/Desktop/Projects/VideoProjects/shaka/shaka_packager'
Updating Clang to 317263-2...
Creating directory /home/usr/Desktop/Projects/VideoProjects/shaka/shaka_packager/src/packager/third_party/llvm-build
Downloading prebuilt clang
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-317263-2.tgz .......... Done.
Creating directory /home/usr/Desktop/Projects/VideoProjects/shaka/shaka_packager/src/packager/third_party/llvm-build/Release+Asserts
clang 317263-2 unpacked
Running hooks:  80% ( 4/ 5)      
________ running 'vpython src/gyp_packager.py --depth=src/packager' in '/home/usr/Desktop/Projects/VideoProjects/shaka/shaka_packager'
Updating projects from gyp files...
Traceback (most recent call last):
  File "src/gyp_packager.py", line 115, in <module>
    sys.exit(gyp.main(args))
  File "/home/usr/Desktop/Projects/VideoProjects/shaka/shaka_packager/src/packager/tools/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/home/usr/Desktop/Projects/VideoProjects/shaka/shaka_packager/src/packager/tools/gyp/pylib/gyp/__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/home/usr/Desktop/Projects/VideoProjects/shaka/shaka_packager/src/packager/tools/gyp/pylib/gyp/generator/ninja.py", line 2469, in GenerateOutput
    pool.map(CallGenerateOutputForConfig, arglists)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
AssertionError: Ninja syntax does not allow newlines
Error: Command 'vpython src/gyp_packager.py --depth=src/packager' returned non-zero exit status 1 in /home/usr/Desktop/Projects/VideoProjects/shaka/shaka_packager

```
Also get the following when I try to run
 ./packager/build/install-build-deps.sh

`ERROR: Only Ubuntu 12.04 (precise), 14.04 (trusty),  14.10 (utopic), 15.04 (vivid), 15.10 (wily) and 16.04 (xenial)  are currently supported` 
Can someone please let me know how to resolve this issue and if there is way to build on Ubuntu 19.10?

**Comment by kqyang** [comment]
This is because the build scripts does not support having two tags in the same CL. I have removed the temporary tags (v.2.4.0p2). It should work now. 

I'm closing this bug as fixed. Let us know if you are still seeing problems. Thanks.

**Comment by sr1990** [comment]
@kqyang Worked! Thanks
